[licenses]
# Only allow licenses compatible with AGPL
clarify = []
allow = [
    "AGPL-3.0-only",
    "GPL-3.0-only",
    "LGPL-3.0-only",
    "MIT",          # compatible with AGPL
    "Apache-2.0",   # compatible with AGPL
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause", # compatible with AGPL
    "ISC",         # compatible with AGPL
    "CC0-1.0",     # compatible with AGPL
    "MPL-2.0",     # compatible with AGPL https://www.fsf.org/blogs/licensing/mpl-2.0-release https://www.mozilla.org/en-US/MPL/2.0/FAQ/#mpl-and-lgpl
    "Unicode-3.0", # Used by unicode-ident crate
    "Zlib",        # compatible with AGPL https://www.gnu.org/licenses/license-list.html#ZLib
]

# Ensure every crate has a valid license file
private = { ignore = true }
confidence-threshold = 0.8

# Don't warn about allowed licenses that aren't currently used
unused-allowed-license = "allow"
