#!/bin/bash
# Patches the AndroidManifest.xml generated by Dioxus to add storage permissions,
# then rebuilds the APK with Gradle.
#
# Required for reading/writing markdown files on Android external storage.
#
# This is a workaround until Dioxus supports Android permissions natively.
# See: https://github.com/DioxusLabs/dioxus/issues/3870
# See: https://github.com/DioxusLabs/dioxus/pull/4842 (draft PR for manifest support)
# See: doc/adr/0009-android-storage-permissions-workaround.md
#
# Requires: xmlstarlet (apt install xmlstarlet)

set -e

ANDROID_PROJECT="target/dx/markdown-neuraxis-dioxus/debug/android/app"
MANIFEST_PATH="$ANDROID_PROJECT/app/src/main/AndroidManifest.xml"
NS="http://schemas.android.com/apk/res/android"

if ! command -v xmlstarlet &> /dev/null; then
    echo "Error: xmlstarlet is required but not installed"
    echo "Install with: apt install xmlstarlet"
    exit 1
fi

if [ ! -f "$MANIFEST_PATH" ]; then
    echo "Error: AndroidManifest.xml not found at $MANIFEST_PATH"
    echo "Run 'dx build --platform android' first to generate it"
    exit 1
fi

echo "Patching AndroidManifest.xml with storage permissions..."

# Check if already patched
if xmlstarlet sel -N android="$NS" -t -v "//uses-permission[@android:name='android.permission.READ_EXTERNAL_STORAGE']/@android:name" "$MANIFEST_PATH" 2>/dev/null | grep -q READ_EXTERNAL_STORAGE; then
    echo "Manifest already patched, skipping patch step"
else
    # Create a temporary file for modifications
    TMP_FILE=$(mktemp)
    cp "$MANIFEST_PATH" "$TMP_FILE"

    # Add storage permissions after existing uses-permission elements
    for PERM in "android.permission.READ_EXTERNAL_STORAGE" \
                "android.permission.WRITE_EXTERNAL_STORAGE" \
                "android.permission.MANAGE_EXTERNAL_STORAGE"; do
        xmlstarlet ed -L \
            -N android="$NS" \
            -s "/manifest" -t elem -n "uses-permission" \
            -i "/manifest/uses-permission[not(@android:name)]" -t attr -n "android:name" -v "$PERM" \
            "$TMP_FILE"
        echo "Added: $PERM"
    done

    # Add requestLegacyExternalStorage="true" to application element (for Android 10)
    xmlstarlet ed -L \
        -N android="$NS" \
        -i "/manifest/application[not(@android:requestLegacyExternalStorage)]" \
        -t attr -n "android:requestLegacyExternalStorage" -v "true" \
        "$TMP_FILE"
    echo "Added: requestLegacyExternalStorage=true"

    # Replace original with patched version
    mv "$TMP_FILE" "$MANIFEST_PATH"

    echo "AndroidManifest.xml patched successfully"
fi

# Rebuild APK with patched manifest
echo ""
echo "Rebuilding APK with Gradle..."
cd "$ANDROID_PROJECT"
./gradlew assembleDebug
cd - > /dev/null

echo ""
echo "APK built at: $ANDROID_PROJECT/app/build/outputs/apk/debug/app-debug.apk"
echo ""
echo "IMPORTANT: For MANAGE_EXTERNAL_STORAGE permission on Android 11+, users must:"
echo "  1. Go to Settings > Apps > markdown-neuraxis > Permissions"
echo "  2. Enable 'All files access'"
